### PR TITLE
Getcompanyinfo

### PR DESCRIPTION
**Pull request by mpherg**

### CODE REVIEW

**Comment by rodolfobandeira** [comment]
@mpherg The reason I ask is because when I try compiling on my MacOS, (Installed libjson via homebrew), I'm getting a compilation error:

```
In file included from main.cpp:1:
./IEX.h:75:19: warning: 'Reader' is deprecated: Use CharReader and CharReaderBuilder instead [-Wdeprecated-declarations]
            Json::Reader jsonReader;
```

@mpherg do you mind sharing the version you have there? `brew info jsoncpp`

Here is what I have: `brew info jsoncpp`

```
brew info jsoncpp
jsoncpp: stable 1.8.4 (bottled), HEAD
Library for interacting with JSON
https://github.com/open-source-parsers/jsoncpp
/usr/local/Cellar/jsoncpp/1.8.4 (23 files, 625.8KB) *
```

**Comment by mpherg** [comment]
I get the same deprecation warning (also using 1.8.4).

**Comment by rodolfobandeira** [comment]
@mpherg I see. So, I'm gonna debug a bit based on #8 and see if I can replace that deprecated method to the suggested one. Thanks @mpherg !

**Comment by mpherg** [comment]
👍

**Pull request merged**
