### PR TITLE
some refactoring

### PR DESCRIPTION
**Pull request by mvilkin**

### CODE REVIEW

**Comment by mvilkin** [comment]
Ok. What is the version? `clang-format-6.0` fails with `error: unknown key 'SplitEmptyFunctionBody'`

**Comment by mpherg** [comment]
We've been using clang-format-5.0, but I'm not opposed to upgrading (latest is [clang 8](https://clang.llvm.org/docs/ClangFormatStyleOptions.html)).

**Comment by mpherg** [comment]
Here's the list of supported versions of clang "out of the box" for various distributions:

Ubuntu 16.04: 6.0
Ubuntu 18.04: 6.0
RHEL 7: 5.0.1 (via SCLO)
MacOS: 8.0 (via Homebrew)

I'm OK going to version 6.

**Comment by mpherg** [comment]
You can also use 5.0 on Ubuntu, so maybe we should just stick with that for now.

**Comment by mvilkin** [comment]
Updated with v5.0

**Comment by rodolfobandeira** [comment]
Build started failing after this PR was merged. Is it compiling well for you guys? @mpherg @mvilkin

**Comment by rodolfobandeira** [comment]
@mvilkin 

Already fixed on master and added Travis-CI to catch future issues like this. Do you mind taking a look [at the fix](https://github.com/rodolfobandeira/iex-cpp-client/commit/8c8d308ba99ac763e9a380ea23247d14ffa3cffe) just to make sure it makes sense? 

Here is the error log:

```
Starting compilation
In file included from IEX.h:6:0,
                 from main.cpp:1:
IEX.h: In function ‘Json::Value IEX::Resources::sendGetRequest(const string&, IEX::Resources::Callback)’:
IEX.h:88:13: error: cannot pass objects of non-trivially-copyable type ‘using Callback = class std::function<long unsigned int(const char*, long unsigned int, long unsigned int, std::basic_string<char>*)> {aka class std::function<long unsigned int(const char*, long unsigned int, long unsigned int, std::basic_string<char>*)>}’ through ‘...’
             curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, callback);
```

**Comment by mvilkin** [comment]
Hmm, weird error. Mb it happens because of differnet compiler versions or flags.
Your solutions seems ok. But if you have no needs to override defaultCallback, you can also remove callback from function arguments.

**Pull request merged**
